### ISSUE TITLE
Some data points have no root label

### ISSUE THREAD

**Issue by jfroy** [raylas/nextdns-exporter#20]
Some data points have no `root` label/attribute, which results in annoying labels in Grafana. I think the NextDNS API is not returning a `root` attribute, looking at the code. Perhaps the exporter could copy `domain` into `root` when `root` is empty.

   
![Screenshot_20230921_092640](https://github.com/raylas/nextdns-exporter/assets/49554/eeab5030-22e0-429a-b9bc-76dff4f2c20a)
![Screenshot_20230921_092844](https://github.com/raylas/nextdns-exporter/assets/49554/d3c1fc8e-dfce-467d-a286-c4c7efa3823a)

**Comment by raylas** [comment]
Seems like a very reasonable idea. I'll maybe take a stab at it during an idle moment.
