### ISSUE TITLE
"Native" alternative available 

### ISSUE THREAD

**Issue by trollybusman** [raylas/nextdns-exporter#29]
Control D DNS daemon which has a native/built in Prometheus exporter recently added "NextDNS mode", which allows their app to be drop in place compatible with NextDNS. Has all the same features of the nextdns CLI and a bunch of unique ones too. 

https://github.com/Control-D-Inc/ctrld/wiki/NextDNS-Mode

https://github.com/Control-D-Inc/ctrld/blob/main/docs/config.md#metrics_query_stats

**Comment by raylas** [comment]
Nice! Thanks for the tip.
